addSbtPlugin("org.scala-js"        % "sbt-scalajs"         % "1.15.0")
addSbtPlugin("org.typelevel"       % "sbt-tpolecat"        % "0.5.0")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"        % "0.9.31")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"         % "0.4.0")
addSbtPlugin("io.spray"            % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly"        % "0.14.10")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalajs-bundler" % "0.21.1")
